import { ConsultationNote, PrescriptionItem } from "@/types";

interface ConsultationData {
  callId: string;
  consultantName: string;
  patientName: string;
  consultationDate: string;
  consultationTime: string;
  duration: number;
  chiefComplaint: string;
  notes: ConsultationNote[];
  prescriptions: PrescriptionItem[];
}

/**
 * Generate a text-based consultation report
 */
export const generateTextReport = (data: ConsultationData): string => {
  const formatTime = (seconds: number): string => {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;

    if (hours > 0) {
      return `${hours}h ${minutes}m ${secs}s`;
    }
    return `${minutes}m ${secs}s`;
  };

  const report = `
═══════════════════════════════════════════════════════════════
                    CONSULTATION REPORT
═══════════════════════════════════════════════════════════════

CONSULTATION DETAILS
────────────────────────────────────────────────────────────────
Consultation ID:     ${data.callId}
Consultant:          ${data.consultantName}
Patient Name:        ${data.patientName}
Date:                ${data.consultationDate}
Time:                ${data.consultationTime}
Duration:            ${formatTime(data.duration)}
Chief Complaint:     ${data.chiefComplaint}

CLINICAL NOTES
────────────────────────────────────────────────────────────────
${
  data.notes.length > 0
    ? data.notes
        .map((note) => {
          const categoryLabel =
            note.category.charAt(0).toUpperCase() + note.category.slice(1);
          return `[${note.timestamp}] (${categoryLabel}):
${note.content}`;
        })
        .join("\n\n")
    : "No notes recorded."
}

PRESCRIPTIONS
────────────────────────────────────────────────────────────────
${
  data.prescriptions.length > 0
    ? data.prescriptions
        .map((p) => {
          return `Medicine:    ${p.medicineName}
Dosage:       ${p.dosage}
Frequency:    ${p.frequency}
Duration:     ${p.duration}
${p.notes ? `Notes:        ${p.notes}` : ""}`;
        })
        .join("\n\n")
    : "No prescriptions issued."
}

SUMMARY
────────────────────────────────────────────────────────────────
Total Notes:         ${data.notes.length}
Total Prescriptions: ${data.prescriptions.length}
Generated:           ${new Date().toLocaleString()}

═══════════════════════════════════════════════════════════════
              Generated by Recommendic Medical Platform
═══════════════════════════════════════════════════════════════
  `;

  return report;
};

/**
 * Generate an HTML report
 */
export const generateHtmlReport = (data: ConsultationData): string => {
  const formatTime = (seconds: number): string => {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;

    if (hours > 0) {
      return `${hours}h ${minutes}m ${secs}s`;
    }
    return `${minutes}m ${secs}s`;
  };

  const getCategoryColor = (category: string): string => {
    const colors: { [key: string]: string } = {
      observation: "#3B82F6",
      diagnosis: "#8B5CF6",
      prescription: "#10B981",
      "follow-up": "#F59E0B",
    };
    return colors[category] || "#6B7280";
  };

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultation Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }
        .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 3px solid #4F46E5;
            padding-bottom: 20px;
        }
        .header h1 {
            font-size: 28px;
            color: #1F2937;
            margin-bottom: 10px;
        }
        .header p {
            color: #6B7280;
            font-size: 14px;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            font-size: 18px;
            font-weight: bold;
            color: #1F2937;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #E5E7EB;
        }
        .details-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin-bottom: 20px;
        }
        .detail-item {
            background: #F9FAFB;
            padding: 12px;
            border-radius: 6px;
        }
        .detail-label {
            font-size: 12px;
            font-weight: 600;
            color: #6B7280;
            text-transform: uppercase;
            margin-bottom: 4px;
        }
        .detail-value {
            font-size: 16px;
            font-weight: 500;
            color: #1F2937;
        }
        .note-item {
            background: #F9FAFB;
            border-left: 4px solid #4F46E5;
            padding: 12px;
            margin-bottom: 12px;
            border-radius: 4px;
        }
        .note-header {
            display: flex;
            justify-content: space-between;
            margin-bottom: 8px;
        }
        .note-category {
            font-size: 12px;
            font-weight: 600;
            color: white;
            padding: 2px 8px;
            border-radius: 3px;
            display: inline-block;
        }
        .note-time {
            font-size: 12px;
            color: #6B7280;
        }
        .note-content {
            font-size: 14px;
            color: #374151;
            line-height: 1.5;
        }
        .prescription-item {
            background: #F0FDF4;
            border: 1px solid #DCFCE7;
            border-left: 4px solid #10B981;
            padding: 15px;
            margin-bottom: 12px;
            border-radius: 4px;
        }
        .prescription-name {
            font-size: 16px;
            font-weight: 600;
            color: #1F2937;
            margin-bottom: 10px;
        }
        .prescription-details {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 10px;
            font-size: 13px;
        }
        .prescription-detail {
            display: flex;
            justify-content: space-between;
        }
        .prescription-label {
            color: #6B7280;
            font-weight: 500;
        }
        .prescription-value {
            color: #1F2937;
            font-weight: 600;
        }
        .prescription-notes {
            margin-top: 10px;
            padding-top: 10px;
            border-top: 1px solid #DCFCE7;
            font-size: 13px;
            color: #374151;
            font-style: italic;
        }
        .summary {
            background: #EFF6FF;
            border: 1px solid #BFDBFE;
            padding: 20px;
            border-radius: 6px;
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            text-align: center;
        }
        .summary-item h3 {
            font-size: 24px;
            color: #1E40AF;
            margin-bottom: 5px;
        }
        .summary-item p {
            font-size: 12px;
            color: #1E40AF;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #E5E7EB;
            text-align: center;
            font-size: 12px;
            color: #6B7280;
        }
        @media print {
            body {
                background: white;
            }
            .container {
                box-shadow: none;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Consultation Report</h1>
            <p>Recommendic Medical Platform</p>
        </div>

        <div class="section">
            <div class="section-title">Consultation Details</div>
            <div class="details-grid">
                <div class="detail-item">
                    <div class="detail-label">Consultation ID</div>
                    <div class="detail-value">${data.callId}</div>
                </div>
                <div class="detail-item">
                    <div class="detail-label">Consultant</div>
                    <div class="detail-value">${data.consultantName}</div>
                </div>
                <div class="detail-item">
                    <div class="detail-label">Patient Name</div>
                    <div class="detail-value">${data.patientName}</div>
                </div>
                <div class="detail-item">
                    <div class="detail-label">Chief Complaint</div>
                    <div class="detail-value">${data.chiefComplaint}</div>
                </div>
                <div class="detail-item">
                    <div class="detail-label">Date</div>
                    <div class="detail-value">${data.consultationDate}</div>
                </div>
                <div class="detail-item">
                    <div class="detail-label">Duration</div>
                    <div class="detail-value">${formatTime(data.duration)}</div>
                </div>
            </div>
        </div>

        ${
          data.notes.length > 0
            ? `
        <div class="section">
            <div class="section-title">Clinical Notes</div>
            ${data.notes
              .map(
                (note) => `
            <div class="note-item" style="border-left-color: ${getCategoryColor(note.category)}">
                <div class="note-header">
                    <span class="note-category" style="background-color: ${getCategoryColor(note.category)}">
                        ${note.category.toUpperCase()}
                    </span>
                    <span class="note-time">${note.timestamp}</span>
                </div>
                <div class="note-content">${note.content}</div>
            </div>
            `,
              )
              .join("")}
        </div>
        `
            : ""
        }

        ${
          data.prescriptions.length > 0
            ? `
        <div class="section">
            <div class="section-title">Prescriptions</div>
            ${data.prescriptions
              .map(
                (p) => `
            <div class="prescription-item">
                <div class="prescription-name">${p.medicineName}</div>
                <div class="prescription-details">
                    <div class="prescription-detail">
                        <span class="prescription-label">Dosage:</span>
                        <span class="prescription-value">${p.dosage}</span>
                    </div>
                    <div class="prescription-detail">
                        <span class="prescription-label">Frequency:</span>
                        <span class="prescription-value">${p.frequency}</span>
                    </div>
                    <div class="prescription-detail">
                        <span class="prescription-label">Duration:</span>
                        <span class="prescription-value">${p.duration}</span>
                    </div>
                </div>
                ${p.notes ? `<div class="prescription-notes"><strong>Notes:</strong> ${p.notes}</div>` : ""}
            </div>
            `,
              )
              .join("")}
        </div>
        `
            : ""
        }

        <div class="section">
            <div class="summary">
                <div class="summary-item">
                    <h3>${data.notes.length}</h3>
                    <p>Clinical Notes</p>
                </div>
                <div class="summary-item">
                    <h3>${data.prescriptions.length}</h3>
                    <p>Prescriptions</p>
                </div>
                <div class="summary-item">
                    <h3>${Math.floor(data.duration / 60)}m</h3>
                    <p>Duration</p>
                </div>
            </div>
        </div>

        <div class="footer">
            <p>Generated on ${new Date().toLocaleString()}</p>
            <p>This report is confidential and intended only for the patient and medical professionals involved in their care.</p>
        </div>
    </div>
</body>
</html>
  `;

  return html;
};

/**
 * Download report as a file
 */
export const downloadReport = (
  content: string,
  filename: string,
  mimeType: string = "text/plain",
) => {
  const element = document.createElement("a");
  element.setAttribute(
    "href",
    `data:${mimeType};charset=utf-8,${encodeURIComponent(content)}`,
  );
  element.setAttribute("download", filename);
  element.style.display = "none";

  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};

/**
 * Export report as PDF
 */
export const downloadPDFReport = async (
  data: ConsultationData,
  filename: string,
) => {
  const htmlContent = generateHtmlReport(data);

  // If html2pdf library is available
  try {
    // You'll need to install html2pdf: npm install html2pdf.js
    const element = document.createElement("div");
    element.innerHTML = htmlContent;

    const opt = {
      margin: 10,
      filename: filename,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { orientation: "portrait", unit: "mm", format: "a4" },
    };

    // @ts-ignore - html2pdf is global
    if (typeof html2pdf !== "undefined") {
      // @ts-ignore
      html2pdf().set(opt).from(element).save();
    } else {
      console.warn(
        "html2pdf library not available. Downloading as HTML instead.",
      );
      downloadReport(
        htmlContent,
        filename.replace(".pdf", ".html"),
        "text/html",
      );
    }
  } catch (error) {
    console.error("Error generating PDF:", error);
  }
};

/**
 * Send report to server
 */
export const sendReportToServer = async (
  data: ConsultationData,
  endpoint: string,
): Promise<boolean> => {
  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        ...data,
        generatedAt: new Date().toISOString(),
      }),
    });

    if (!response.ok) {
      throw new Error(`Server error: ${response.statusText}`);
    }

    return true;
  } catch (error) {
    console.error("Error sending report to server:", error);
    return false;
  }
};
